### ISSUE TITLE
Incorrect links on components page

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2144]
https://eds.equinor.com/0b0c666ab/p/99b362-components

Links need updating - only point to front page.

**Comment by Hjaf** [comment]
Another broken link here:
[https://eds.equinor.com/0b0c666ab/p/53f982-grid-alignment](https://eds.equinor.com/0b0c666ab/p/53f982-grid-alignment) 

Link to grid
"https://eds.equinor.com/guidelines/grid/" 
(actual link should be https://eds.equinor.com/0b0c666ab/p/529628-grid/b/33fa25 ?)

**Comment by BeckyBrekke** [comment]
I fixed the grid link. Can you check it here in this preview mode please and see that it is correct @Hjaf  ? 
https://zeroheight.com/0b0c666ab/v/latest/p/53f982-grid-alignment

**Comment by Hjaf** [comment]
Its still the same it seems, just to clarify which link I'm referring to:
![image](https://user-images.githubusercontent.com/50009020/164464519-b7bfed13-f6b5-4d6c-b97d-87fea10befb9.png)

**Comment by BeckyBrekke** [comment]
@Hjaf That is where I changed it. I think it's a caching issue. When I opened a new Chrome window, copied and pasted the link in, and tried the link, then it worked. Can you try again? https://zeroheight.com/0b0c666ab/v/latest/p/53f982-grid-alignment
